# -*- coding: utf-8 -*-
"""catdog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sofXJXFz6rLxEewOYskBNGKYnzYNDHKn
"""

# ============================================================================
# CATS vs DOGS — CNN FROM SCRATCH
# Adapting Lab 2 techniques (Dropout, BatchNorm, Early Stopping,
# LR Scheduling, Optimizer comparison) from MNIST to a real image dataset.
# Run this in Google Colab (GPU runtime recommended: Runtime > Change runtime type > GPU)
# ============================================================================

# ── STEP 0: Install & download dataset ─────────────────────────────────────
!pip install kagglehub -q

import kagglehub
path = kagglehub.dataset_download("haroon669/cats-vs-dogs-dataset-10k-cat-10k-dog-images")
print("Dataset downloaded to:", path)

# ── STEP 0b: Inspect folder structure (IMPORTANT — run this first!) ───────
import os
print("\nFolder structure (first 2 levels):")
for root, dirs, files in os.walk(path):
    depth = root.replace(path, '').count(os.sep)
    if depth > 1:
        continue
    indent = '  ' * depth
    print(f'{indent}{os.path.basename(root) or root}/  ({len(files)} files)')
    for d in dirs:
        print(f'{indent}  {d}/')

# NOTE: Most Kaggle "cats vs dogs" datasets have a structure like:
#   path/
#     Cat/   (or "cats", "Dog", "dogs" — check the printout above)
#     Dog/
# If your structure is different (e.g. nested one level deeper, or
# already split into train/test), update DATA_DIR below accordingly.

# DATA_DIR = path   # <-- change this if your class folders are nested, e.g. path + "/PetImages"

# ── STEP 1: Imports ─────────────────────────────────────────────────────────
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

print('TF version:', tf.__version__)

# ── STEP 2: Hyperparameter Configuration Block ──────────────────────────────
IMG_SIZE = 128             # Images resized to IMG_SIZE x IMG_SIZE (cats/dogs photos vary in size)
EPOCHS = 25                # Max epochs — Early Stopping will likely stop sooner
BATCH_SIZE = 32            # Smaller than MNIST since images are bigger (memory)
LEARNING_RATE = 0.001      # Starting LR for the optimizer

DROPOUT_RATE = 0.3         # Fraction of neurons dropped (try 0.2–0.5)
USE_BATCH_NORM = True      # Set False to compare training stability without BN
USE_AUGMENTATION = True    # Real photos benefit a lot from augmentation (unlike MNIST digits)

ES_PATIENCE = 5            # Stop if val_loss doesn't improve for 5 epochs
ES_MIN_DELTA = 0.001

LR_PATIENCE = 3            # Reduce LR if val_loss plateaus for 3 epochs
LR_FACTOR = 0.5
LR_MIN = 1e-6

OPTIMIZER_NAME = 'adam'    # 'adam', 'sgd', or 'rmsprop'

print(f'Config: IMG_SIZE={IMG_SIZE}, LR={LEARNING_RATE}, Dropout={DROPOUT_RATE}, '
      f'BatchNorm={USE_BATCH_NORM}, Augmentation={USE_AUGMENTATION}')
print(f'Optimizer: {OPTIMIZER_NAME}, Batch: {BATCH_SIZE}, Max Epochs: {EPOCHS}')

# ── STEP 3: Load and preprocess data ────────────────────────────────────────
# image_dataset_from_directory auto-infers class labels from subfolder names
train_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'train'),
    # validation_split=0.2, # Not needed as data is already split into train/test folders
    # subset='training',    # Not needed as we are pointing directly to the train folder
    seed=42,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode='binary'        # cat=0, dog=1 (or vice versa — check class_names below)
)

val_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'test'),
    # validation_split=0.2, # Not needed as data is already split into train/test folders
    # subset='validation',  # Not needed as we are pointing directly to the test folder
    seed=42,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode='binary'
)

class_names = train_ds.class_names
print('Classes:', class_names)

# Normalize pixel values to [0,1]
normalization_layer = layers.Rescaling(1./255)

# Data augmentation (only applied during training, not validation)
data_augmentation = keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
], name='augmentation')

def prepare(ds, training=False):
    ds = ds.map(lambda x, y: (normalization_layer(x), y))
    if training and USE_AUGMENTATION:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y))
    return ds.prefetch(tf.data.AUTOTUNE)

train_ds_prepped = prepare(train_ds, training=True)
val_ds_prepped = prepare(val_ds, training=False)

# ── STEP 4: Build the CNN from scratch ──────────────────────────────────────
# Architecture: Conv -> BN -> Pool -> Dropout, repeated, deeper than Lab 2
# because cat/dog photos need more capacity than MNIST digits.

def build_model(dropout_rate, use_batch_norm, optimizer_name, learning_rate, img_size):
    model = keras.Sequential(name='CatsDogs_CNN_Scratch')

    # ── CONV BLOCK 1 ──────────────────────────────────────────────────────
    model.add(layers.Conv2D(32, (3, 3), activation='relu', padding='same',
                             input_shape=(img_size, img_size, 3)))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate))

    # ── CONV BLOCK 2 ──────────────────────────────────────────────────────
    model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate))

    # ── CONV BLOCK 3 ──────────────────────────────────────────────────────
    model.add(layers.Conv2D(128, (3, 3), activation='relu', padding='same'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate))

    # ── CONV BLOCK 4 (extra depth vs Lab 2, since real photos are harder) ─
    model.add(layers.Conv2D(256, (3, 3), activation='relu', padding='same'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate / 2))

    # ── CLASSIFIER HEAD ───────────────────────────────────────────────────
    model.add(layers.GlobalAveragePooling2D())   # Lighter than Flatten for large feature maps
    model.add(layers.Dense(256, activation='relu'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(dropout_rate))
    model.add(layers.Dense(1, activation='sigmoid'))   # Binary classification: cat vs dog

    # ── OPTIMIZER SELECTION ───────────────────────────────────────────────
    if optimizer_name == 'adam':
        opt = keras.optimizers.Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        opt = keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.9)
    elif optimizer_name == 'rmsprop':
        opt = keras.optimizers.RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError(f'Unknown optimizer: {optimizer_name}')

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',     # binary, not categorical (only 2 classes)
        metrics=['accuracy']
    )
    return model

model = build_model(DROPOUT_RATE, USE_BATCH_NORM, OPTIMIZER_NAME, LEARNING_RATE, IMG_SIZE)
model.summary()

# ── STEP 5: Callbacks ────────────────────────────────────────────────────────
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=ES_PATIENCE,
    min_delta=ES_MIN_DELTA,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=LR_FACTOR,
    patience=LR_PATIENCE,
    min_lr=LR_MIN,
    verbose=1
)

checkpoint = ModelCheckpoint(
    'best_catsdogs_model.h5',
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

callbacks = [early_stop, reduce_lr, checkpoint]
print('Callbacks configured: EarlyStopping, ReduceLROnPlateau, ModelCheckpoint')

# ── STEP 6: Train ────────────────────────────────────────────────────────────
history = model.fit(
    train_ds_prepped,
    validation_data=val_ds_prepped,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1
)

actual_epochs = len(history.history['loss'])
print(f'Training stopped after {actual_epochs} epochs (max was {EPOCHS})')

# ── STEP 7: Evaluate and plot ────────────────────────────────────────────────
test_loss, test_acc = model.evaluate(val_ds_prepped, verbose=0)
print(f'Validation Accuracy: {test_acc:.4f} | Validation Loss: {test_loss:.4f}')

fig, axes = plt.subplots(1, 3, figsize=(18, 4))

axes[0].plot(history.history['accuracy'], label='Train Acc', color='blue')
axes[0].plot(history.history['val_accuracy'], label='Val Acc', color='orange')
axes[0].set_title(f'Accuracy ({OPTIMIZER_NAME.upper()})')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
axes[0].legend(); axes[0].grid(True)

axes[1].plot(history.history['loss'], label='Train Loss', color='blue')
axes[1].plot(history.history['val_loss'], label='Val Loss', color='orange')
axes[1].set_title('Loss')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].legend(); axes[1].grid(True)

if 'lr' in history.history:
    axes[2].plot(history.history['lr'], color='green', marker='o', markersize=4)
    axes[2].set_title('Learning Rate Schedule')
    axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('Learning Rate')
    axes[2].set_yscale('log')
    axes[2].grid(True)

plt.suptitle(f'Cats vs Dogs CNN | Dropout={DROPOUT_RATE} | BN={USE_BATCH_NORM} | Opt={OPTIMIZER_NAME}',
             fontsize=12)
plt.tight_layout(); plt.show()

# ── STEP 8: Overfitting analysis ─────────────────────────────────────────────
train_acc_final = history.history['accuracy'][-1]
val_acc_final = history.history['val_accuracy'][-1]
gap = train_acc_final - val_acc_final

print(f'Train Accuracy (last epoch): {train_acc_final:.4f}')
print(f'Val Accuracy (last epoch): {val_acc_final:.4f}')
print(f'Accuracy Gap: {gap:.4f}')

if gap > 0.05:
    print('WARNING: Large gap detected -> model may be overfitting')
    print('Try: increase DROPOUT_RATE, add more augmentation, or reduce model size')
elif gap < 0.02:
    print('GOOD: Small gap -> model generalizes well')
else:
    print('MODERATE: Some gap is normal -- monitor with more data/epochs')

# ── STEP 9: Visualize predictions with confidence ───────────────────────────
images_batch, labels_batch = next(iter(val_ds_prepped))
predictions = model.predict(images_batch[:25])
predicted_classes = (predictions > 0.5).astype(int).flatten()
confidence_scores = np.where(predictions.flatten() > 0.5, predictions.flatten(), 1 - predictions.flatten())
true_classes = labels_batch.numpy().flatten().astype(int)[:25]

plt.figure(figsize=(16, 8))
for i in range(min(25, len(images_batch))):
    plt.subplot(5, 5, i + 1)
    plt.imshow(images_batch[i].numpy())
    correct = predicted_classes[i] == true_classes[i]
    color = 'green' if correct else 'red'
    plt.title(
        f'P:{class_names[predicted_classes[i]]} ({confidence_scores[i]:.0%})\nT:{class_names[true_classes[i]]}',
        color=color, fontsize=8
    )
    plt.axis('off')
plt.suptitle('Predictions with Confidence | Green=Correct Red=Wrong', fontsize=12)
plt.tight_layout(); plt.show()

# ── STEP 10: Optimizer comparison (run AFTER Steps 1-9, optional) ──────────
optimizers_to_compare = ['adam', 'sgd', 'rmsprop']
results = {}
histories = {}

for opt_name in optimizers_to_compare:
    print(f'\nTraining with optimizer: {opt_name.upper()}')
    print('=' * 40)
    temp_model = build_model(
        dropout_rate=0.3,
        use_batch_norm=True,
        optimizer_name=opt_name,
        learning_rate=0.001,
        img_size=IMG_SIZE
    )
    temp_es = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    temp_history = temp_model.fit(
        train_ds_prepped,
        validation_data=val_ds_prepped,
        epochs=20,
        callbacks=[temp_es],
        verbose=0
    )
    _, acc = temp_model.evaluate(val_ds_prepped, verbose=0)
    results[opt_name] = acc
    histories[opt_name] = temp_history
    print(f'{opt_name.upper()} -> Validation Accuracy: {acc:.4f}')

plt.figure(figsize=(12, 4))
for opt_name, h in histories.items():
    plt.plot(h.history['val_accuracy'], label=f'{opt_name} (val={results[opt_name]:.4f})')
plt.title('Optimizer Comparison: Validation Accuracy')
plt.xlabel('Epoch'); plt.ylabel('Val Accuracy')
plt.legend(); plt.grid(True); plt.show()

"""**0.5 dropout and 30 epochs**"""

# ============================================================================
# CATS vs DOGS — CNN FROM SCRATCH
# Adapting Lab 2 techniques (Dropout, BatchNorm, Early Stopping,
# LR Scheduling, Optimizer comparison) from MNIST to a real image dataset.
# Run this in Google Colab (GPU runtime recommended: Runtime > Change runtime type > GPU)
# ============================================================================

# ── STEP 0: Install & download dataset ─────────────────────────────────────
!pip install kagglehub -q

import kagglehub
path = kagglehub.dataset_download("haroon669/cats-vs-dogs-dataset-10k-cat-10k-dog-images")
print("Dataset downloaded to:", path)

# ── STEP 0b: Inspect folder structure (IMPORTANT — run this first!) ───────
import os
print("\nFolder structure (first 2 levels):")
for root, dirs, files in os.walk(path):
    depth = root.replace(path, '').count(os.sep)
    if depth > 1:
        continue
    indent = '  ' * depth
    print(f'{indent}{os.path.basename(root) or root}/  ({len(files)} files)')
    for d in dirs:
        print(f'{indent}  {d}/')

# NOTE: Most Kaggle "cats vs dogs" datasets have a structure like:
#   path/
#     Cat/   (or "cats", "Dog", "dogs" — check the printout above)
#     Dog/
# If your structure is different (e.g. nested one level deeper, or
# already split into train/test), update DATA_DIR below accordingly.

# DATA_DIR = path   # <-- change this if your class folders are nested, e.g. path + "/PetImages"

# ── STEP 1: Imports ─────────────────────────────────────────────────────────
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

print('TF version:', tf.__version__)

# ── STEP 2: Hyperparameter Configuration Block ──────────────────────────────
IMG_SIZE = 128             # Images resized to IMG_SIZE x IMG_SIZE (cats/dogs photos vary in size)
EPOCHS = 30                # Max epochs — Early Stopping will likely stop sooner
BATCH_SIZE = 32            # Smaller than MNIST since images are bigger (memory)
LEARNING_RATE = 0.001      # Starting LR for the optimizer

DROPOUT_RATE = 0.5         # Fraction of neurons dropped (try 0.2–0.5)
USE_BATCH_NORM = True      # Set False to compare training stability without BN
USE_AUGMENTATION = True    # Real photos benefit a lot from augmentation (unlike MNIST digits)

ES_PATIENCE = 5            # Stop if val_loss doesn't improve for 5 epochs
ES_MIN_DELTA = 0.001

LR_PATIENCE = 3            # Reduce LR if val_loss plateaus for 3 epochs
LR_FACTOR = 0.5
LR_MIN = 1e-6

OPTIMIZER_NAME = 'adam'    # 'adam', 'sgd', or 'rmsprop'

print(f'Config: IMG_SIZE={IMG_SIZE}, LR={LEARNING_RATE}, Dropout={DROPOUT_RATE}, '
      f'BatchNorm={USE_BATCH_NORM}, Augmentation={USE_AUGMENTATION}')
print(f'Optimizer: {OPTIMIZER_NAME}, Batch: {BATCH_SIZE}, Max Epochs: {EPOCHS}')

# ── STEP 3: Load and preprocess data ────────────────────────────────────────
# image_dataset_from_directory auto-infers class labels from subfolder names
train_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'train'),
    # validation_split=0.2, # Not needed as data is already split into train/test folders
    # subset='training',    # Not needed as we are pointing directly to the train folder
    seed=42,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode='binary'        # cat=0, dog=1 (or vice versa — check class_names below)
)

val_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'test'),
    # validation_split=0.2, # Not needed as data is already split into train/test folders
    # subset='validation',  # Not needed as we are pointing directly to the test folder
    seed=42,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    label_mode='binary'
)

class_names = train_ds.class_names
print('Classes:', class_names)

# Normalize pixel values to [0,1]
normalization_layer = layers.Rescaling(1./255)

# Data augmentation (only applied during training, not validation)
data_augmentation = keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
], name='augmentation')

def prepare(ds, training=False):
    ds = ds.map(lambda x, y: (normalization_layer(x), y))
    if training and USE_AUGMENTATION:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y))
    return ds.prefetch(tf.data.AUTOTUNE)

train_ds_prepped = prepare(train_ds, training=True)
val_ds_prepped = prepare(val_ds, training=False)

# ── STEP 4: Build the CNN from scratch ──────────────────────────────────────
# Architecture: Conv -> BN -> Pool -> Dropout, repeated, deeper than Lab 2
# because cat/dog photos need more capacity than MNIST digits.

def build_model(dropout_rate, use_batch_norm, optimizer_name, learning_rate, img_size):
    model = keras.Sequential(name='CatsDogs_CNN_Scratch')

    # ── CONV BLOCK 1 ──────────────────────────────────────────────────────
    model.add(layers.Conv2D(32, (3, 3), activation='relu', padding='same',
                             input_shape=(img_size, img_size, 3)))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate))

    # ── CONV BLOCK 2 ──────────────────────────────────────────────────────
    model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate))

    # ── CONV BLOCK 3 ──────────────────────────────────────────────────────
    model.add(layers.Conv2D(128, (3, 3), activation='relu', padding='same'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Dropout(dropout_rate))

    # ── CLASSIFIER HEAD ───────────────────────────────────────────────────
    model.add(layers.GlobalAveragePooling2D())   # Lighter than Flatten for large feature maps
    model.add(layers.Dense(256, activation='relu'))
    if use_batch_norm:
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(dropout_rate))
    model.add(layers.Dense(1, activation='sigmoid'))   # Binary classification: cat vs dog

    # ── OPTIMIZER SELECTION ───────────────────────────────────────────────
    if optimizer_name == 'adam':
        opt = keras.optimizers.Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        opt = keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.9)
    elif optimizer_name == 'rmsprop':
        opt = keras.optimizers.RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError(f'Unknown optimizer: {optimizer_name}')

    model.compile(
        optimizer=opt,
        loss='binary_crossentropy',     # binary, not categorical (only 2 classes)
        metrics=['accuracy']
    )
    return model

model = build_model(DROPOUT_RATE, USE_BATCH_NORM, OPTIMIZER_NAME, LEARNING_RATE, IMG_SIZE)
model.summary()

# ── STEP 5: Callbacks ────────────────────────────────────────────────────────
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=ES_PATIENCE,
    min_delta=ES_MIN_DELTA,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=LR_FACTOR,
    patience=LR_PATIENCE,
    min_lr=LR_MIN,
    verbose=1
)

checkpoint = ModelCheckpoint(
    'best_catsdogs_model.h5',
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

callbacks = [early_stop, reduce_lr, checkpoint]
print('Callbacks configured: EarlyStopping, ReduceLROnPlateau, ModelCheckpoint')

# ── STEP 6: Train ────────────────────────────────────────────────────────────
history = model.fit(
    train_ds_prepped,
    validation_data=val_ds_prepped,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1
)

actual_epochs = len(history.history['loss'])
print(f'Training stopped after {actual_epochs} epochs (max was {EPOCHS})')

# ── STEP 7: Evaluate and plot ────────────────────────────────────────────────
test_loss, test_acc = model.evaluate(val_ds_prepped, verbose=0)
print(f'Validation Accuracy: {test_acc:.4f} | Validation Loss: {test_loss:.4f}')

fig, axes = plt.subplots(1, 3, figsize=(18, 4))

axes[0].plot(history.history['accuracy'], label='Train Acc', color='blue')
axes[0].plot(history.history['val_accuracy'], label='Val Acc', color='orange')
axes[0].set_title(f'Accuracy ({OPTIMIZER_NAME.upper()})')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
axes[0].legend(); axes[0].grid(True)

axes[1].plot(history.history['loss'], label='Train Loss', color='blue')
axes[1].plot(history.history['val_loss'], label='Val Loss', color='orange')
axes[1].set_title('Loss')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].legend(); axes[1].grid(True)

if 'lr' in history.history:
    axes[2].plot(history.history['lr'], color='green', marker='o', markersize=4)
    axes[2].set_title('Learning Rate Schedule')
    axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('Learning Rate')
    axes[2].set_yscale('log')
    axes[2].grid(True)

plt.suptitle(f'Cats vs Dogs CNN | Dropout={DROPOUT_RATE} | BN={USE_BATCH_NORM} | Opt={OPTIMIZER_NAME}',
             fontsize=12)
plt.tight_layout(); plt.show()

# ── STEP 8: Overfitting analysis ─────────────────────────────────────────────
train_acc_final = history.history['accuracy'][-1]
val_acc_final = history.history['val_accuracy'][-1]
gap = train_acc_final - val_acc_final

print(f'Train Accuracy (last epoch): {train_acc_final:.4f}')
print(f'Val Accuracy (last epoch): {val_acc_final:.4f}')
print(f'Accuracy Gap: {gap:.4f}')

if gap > 0.05:
    print('WARNING: Large gap detected -> model may be overfitting')
    print('Try: increase DROPOUT_RATE, add more augmentation, or reduce model size')
elif gap < 0.02:
    print('GOOD: Small gap -> model generalizes well')
else:
    print('MODERATE: Some gap is normal -- monitor with more data/epochs')

# ── STEP 9: Visualize predictions with confidence ───────────────────────────
images_batch, labels_batch = next(iter(val_ds_prepped))
predictions = model.predict(images_batch[:25])
predicted_classes = (predictions > 0.5).astype(int).flatten()
confidence_scores = np.where(predictions.flatten() > 0.5, predictions.flatten(), 1 - predictions.flatten())
true_classes = labels_batch.numpy().flatten().astype(int)[:25]

plt.figure(figsize=(16, 8))
for i in range(min(25, len(images_batch))):
    plt.subplot(5, 5, i + 1)
    plt.imshow(images_batch[i].numpy())
    correct = predicted_classes[i] == true_classes[i]
    color = 'green' if correct else 'red'
    plt.title(
        f'P:{class_names[predicted_classes[i]]} ({confidence_scores[i]:.0%})\nT:{class_names[true_classes[i]]}',
        color=color, fontsize=8
    )
    plt.axis('off')
plt.suptitle('Predictions with Confidence | Green=Correct Red=Wrong', fontsize=12)
plt.tight_layout(); plt.show()

# ── STEP 10: Optimizer comparison (run AFTER Steps 1-9, optional) ──────────
optimizers_to_compare = ['adam', 'sgd', 'rmsprop']
results = {}
histories = {}

for opt_name in optimizers_to_compare:
    print(f'\nTraining with optimizer: {opt_name.upper()}')
    print('=' * 40)
    temp_model = build_model(
        dropout_rate=0.3,
        use_batch_norm=True,
        optimizer_name=opt_name,
        learning_rate=0.001,
        img_size=IMG_SIZE
    )
    temp_es = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    temp_history = temp_model.fit(
        train_ds_prepped,
        validation_data=val_ds_prepped,
        epochs=20,
        callbacks=[temp_es],
        verbose=0
    )
    _, acc = temp_model.evaluate(val_ds_prepped, verbose=0)
    results[opt_name] = acc
    histories[opt_name] = temp_history
    print(f'{opt_name.upper()} -> Validation Accuracy: {acc:.4f}')

plt.figure(figsize=(12, 4))
for opt_name, h in histories.items():
    plt.plot(h.history['val_accuracy'], label=f'{opt_name} (val={results[opt_name]:.4f})')
plt.title('Optimizer Comparison: Validation Accuracy')
plt.xlabel('Epoch'); plt.ylabel('Val Accuracy')
plt.legend(); plt.grid(True); plt.show()

# ============================================================================
# CATS vs DOGS — CNN HYPERPARAMETER EXPERIMENTS
# Toggle EXPERIMENT below to switch configs (A/B/C/D)
# ============================================================================

!pip install kagglehub -q

import kagglehub, os
path = kagglehub.dataset_download("haroon669/cats-vs-dogs-dataset-10k-cat-10k-dog-images")
print("Dataset downloaded to:", path)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, LearningRateScheduler

print('TF version:', tf.__version__)

# ── EXPERIMENT SELECTOR ──────────────────────────────────────────────────
EXPERIMENT = 'A'   # 'A', 'B', 'C', or 'D'

CONFIGS = {
    'A': dict(conv_filters=[32,64,128,256], dropout_schedule=[0.2,0.25,0.3,0.3],
              pooling='avg', optimizer='adam', lr=0.001, lr_schedule='plateau',
              dense_units=256, epochs=100),
}
cfg = CONFIGS[EXPERIMENT]
print(f'Running Experiment {EXPERIMENT}: {cfg}')

IMG_SIZE = 128
BATCH_SIZE = 32
USE_BATCH_NORM = True
USE_AUGMENTATION = True
ES_PATIENCE = 5
ES_MIN_DELTA = 0.001
LR_PATIENCE = 3
LR_FACTOR = 0.5
LR_MIN = 1e-6

# ── DATA ──────────────────────────────────────────────────────────────────
train_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'train'), seed=42, image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, label_mode='binary')

val_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'test'), seed=42, image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, label_mode='binary')

class_names = train_ds.class_names
print('Classes:', class_names)

normalization_layer = layers.Rescaling(1./255)
data_augmentation = keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
], name='augmentation')

def prepare(ds, training=False):
    ds = ds.map(lambda x, y: (normalization_layer(x), y))
    if training and USE_AUGMENTATION:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y))
    return ds.prefetch(tf.data.AUTOTUNE)

train_ds_prepped = prepare(train_ds, training=True)
val_ds_prepped = prepare(val_ds, training=False)

# ── MODEL BUILDER ─────────────────────────────────────────────────────────
def build_model(cfg, img_size):
    model = keras.Sequential(name=f'CatsDogs_Exp_{EXPERIMENT}')

    for i, (filters, drop) in enumerate(zip(cfg['conv_filters'], cfg['dropout_schedule'])):
        if i == 0:
            model.add(layers.Conv2D(filters, (3,3), activation='relu', padding='same',
                                     input_shape=(img_size, img_size, 3)))
        else:
            model.add(layers.Conv2D(filters, (3,3), activation='relu', padding='same'))
        if USE_BATCH_NORM:
            model.add(layers.BatchNormalization())
        model.add(layers.MaxPooling2D((2,2)))
        model.add(layers.Dropout(drop))

    # Pooling head: global average vs global max
    if cfg['pooling'] == 'avg':
        model.add(layers.GlobalAveragePooling2D())
    else:
        model.add(layers.GlobalMaxPooling2D())

    model.add(layers.Dense(cfg['dense_units'], activation='relu'))
    if USE_BATCH_NORM:
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(cfg['dropout_schedule'][-1]))
    model.add(layers.Dense(1, activation='sigmoid'))

    # Optimizer
    if cfg['optimizer'] == 'adam':
        opt = keras.optimizers.Adam(learning_rate=cfg['lr'])
    elif cfg['optimizer'] == 'adamw':
        opt = keras.optimizers.AdamW(learning_rate=cfg['lr'], weight_decay=1e-4)
    elif cfg['optimizer'] == 'sgd':
        opt = keras.optimizers.SGD(learning_rate=cfg['lr'], momentum=0.9)
    elif cfg['optimizer'] == 'rmsprop':
        opt = keras.optimizers.RMSprop(learning_rate=cfg['lr'])
    else:
        raise ValueError(f"Unknown optimizer: {cfg['optimizer']}")

    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    return model

model = build_model(cfg, IMG_SIZE)
model.summary()

# ── CALLBACKS ─────────────────────────────────────────────────────────────
callbacks = [
    EarlyStopping(monitor='val_loss', patience=ES_PATIENCE, min_delta=ES_MIN_DELTA,
                  restore_best_weights=True, verbose=1),
    ModelCheckpoint(f'best_model_exp{EXPERIMENT}.h5', monitor='val_accuracy',
                     save_best_only=True, verbose=1),
]

if cfg['lr_schedule'] == 'plateau':
    callbacks.append(ReduceLROnPlateau(monitor='val_loss', factor=LR_FACTOR,
                                        patience=LR_PATIENCE, min_lr=LR_MIN, verbose=1))
elif cfg['lr_schedule'] == 'cosine':
    def cosine_decay(epoch, lr):
        return cfg['lr'] * 0.5 * (1 + np.cos(np.pi * epoch / cfg['epochs']))
    callbacks.append(LearningRateScheduler(cosine_decay, verbose=1))

print(f"Callbacks: EarlyStopping, ModelCheckpoint, {cfg['lr_schedule']} LR schedule")

# ── TRAIN ─────────────────────────────────────────────────────────────────
history = model.fit(
    train_ds_prepped, validation_data=val_ds_prepped,
    epochs=cfg['epochs'], callbacks=callbacks, verbose=1
)

actual_epochs = len(history.history['loss'])
print(f'Training stopped after {actual_epochs} epochs (max was {cfg["epochs"]})')

# ── EVALUATE & PLOT ───────────────────────────────────────────────────────
test_loss, test_acc = model.evaluate(val_ds_prepped, verbose=0)
print(f'[Experiment {EXPERIMENT}] Validation Accuracy: {test_acc:.4f} | Loss: {test_loss:.4f}')

fig, axes = plt.subplots(1, 3, figsize=(18, 4))
axes[0].plot(history.history['accuracy'], label='Train Acc')
axes[0].plot(history.history['val_accuracy'], label='Val Acc')
axes[0].set_title(f'Accuracy (Exp {EXPERIMENT})'); axes[0].legend(); axes[0].grid(True)

axes[1].plot(history.history['loss'], label='Train Loss')
axes[1].plot(history.history['val_loss'], label='Val Loss')
axes[1].set_title('Loss'); axes[1].legend(); axes[1].grid(True)

lr_key = 'lr' if 'lr' in history.history else None
if lr_key:
    axes[2].plot(history.history[lr_key], color='green', marker='o', markersize=4)
    axes[2].set_title('LR Schedule'); axes[2].set_yscale('log'); axes[2].grid(True)

plt.suptitle(f'Exp {EXPERIMENT}: filters={cfg["conv_filters"]}, opt={cfg["optimizer"]}, '
             f'pooling={cfg["pooling"]}, dense={cfg["dense_units"]}', fontsize=11)
plt.tight_layout(); plt.show()

# ── OVERFITTING CHECK ─────────────────────────────────────────────────────
gap = history.history['accuracy'][-1] - history.history['val_accuracy'][-1]
print(f'Accuracy Gap: {gap:.4f}')
print('WARNING: possible overfitting' if gap > 0.05 else 'GOOD generalization' if gap < 0.02 else 'MODERATE gap')

# ── SAMPLE PREDICTIONS ON TEST SET ─────────────────────────────────────────
images_batch, labels_batch = next(iter(val_ds_prepped))
predictions = model.predict(images_batch[:25])
predicted_classes = (predictions > 0.5).astype(int).flatten()
confidence_scores = np.where(predictions.flatten() > 0.5, predictions.flatten(), 1 - predictions.flatten())
true_classes = labels_batch.numpy().flatten().astype(int)[:25]

plt.figure(figsize=(16, 8))
for i in range(min(25, len(images_batch))):
    plt.subplot(5, 5, i + 1)
    plt.imshow(images_batch[i].numpy())
    correct = predicted_classes[i] == true_classes[i]
    color = 'green' if correct else 'red'
    plt.title(
        f'P:{class_names[predicted_classes[i]]} ({confidence_scores[i]:.0%})\nT:{class_names[true_classes[i]]}',
        color=color, fontsize=8
    )
    plt.axis('off')
plt.suptitle(f'Experiment {exp_name if "exp_name" in dir() else EXPERIMENT}: Sample Predictions', fontsize=12)
plt.tight_layout(); plt.show()

# ── TRAINING EFFICIENCY SUMMARY ─────────────────────────────────────────────
import time
# (wrap your model.fit() call with time.time() before/after to capture this)
print(f'Total epochs run: {len(history.history["loss"])}')
print(f'Final train acc: {history.history["accuracy"][-1]:.4f}')
print(f'Final val acc: {history.history["val_accuracy"][-1]:.4f}')
print(f'Best val acc (across all epochs): {max(history.history["val_accuracy"]):.4f}')
print(f'Final LR: {history.history["lr"][-1] if "lr" in history.history else "N/A (cosine custom)"}')

# ============================================================================
# CATS vs DOGS — OPTIMIZER COMPARISON (Adam vs AdamW vs SGD vs RMSprop)
# Using best architecture found so far (Experiment D: 4 conv blocks, cosine LR)
# ============================================================================

!pip install kagglehub -q

import kagglehub, os, time
path = kagglehub.dataset_download("haroon669/cats-vs-dogs-dataset-10k-cat-10k-dog-images")
print("Dataset downloaded to:", path)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler

print('TF version:', tf.__version__)

# ── FIXED ARCHITECTURE SETTINGS (best config so far) ────────────────────────
IMG_SIZE = 128
BATCH_SIZE = 32
CONV_FILTERS = [32, 64, 128, 256]          # 4 conv blocks
DROPOUT_SCHEDULE = [0.2, 0.25, 0.3, 0.3]   # graduated dropout
POOLING = 'avg'                             # GlobalAveragePooling2D
DENSE_UNITS = 512
USE_BATCH_NORM = True
USE_AUGMENTATION = True
EPOCHS = 25
BASE_LR = 0.001

ES_PATIENCE = 5
ES_MIN_DELTA = 0.001

# ── OPTIMIZERS TO COMPARE ────────────────────────────────────────────────────
OPTIMIZERS_TO_TEST = ['adam', 'adamw', 'sgd', 'rmsprop']

# ── DATA (loaded once, reused) ───────────────────────────────────────────────
train_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'train'), seed=42, image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, label_mode='binary')

val_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'test'), seed=42, image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, label_mode='binary')

class_names = train_ds.class_names
print('Classes:', class_names)

normalization_layer = layers.Rescaling(1./255)
data_augmentation = keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
], name='augmentation')

def prepare(ds, training=False):
    ds = ds.map(lambda x, y: (normalization_layer(x), y))
    if training and USE_AUGMENTATION:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y))
    return ds.prefetch(tf.data.AUTOTUNE)

train_ds_prepped = prepare(train_ds, training=True)
val_ds_prepped = prepare(val_ds, training=False)

# ── MODEL BUILDER (architecture fixed, optimizer swapped) ───────────────────
def build_model(optimizer_name, img_size):
    model = keras.Sequential(name=f'CatsDogs_{optimizer_name}')

    for i, (filters, drop) in enumerate(zip(CONV_FILTERS, DROPOUT_SCHEDULE)):
        if i == 0:
            model.add(layers.Conv2D(filters, (3,3), activation='relu', padding='same',
                                     input_shape=(img_size, img_size, 3)))
        else:
            model.add(layers.Conv2D(filters, (3,3), activation='relu', padding='same'))
        if USE_BATCH_NORM:
            model.add(layers.BatchNormalization())
        model.add(layers.MaxPooling2D((2,2)))
        model.add(layers.Dropout(drop))

    if POOLING == 'avg':
        model.add(layers.GlobalAveragePooling2D())
    else:
        model.add(layers.GlobalMaxPooling2D())

    model.add(layers.Dense(DENSE_UNITS, activation='relu'))
    if USE_BATCH_NORM:
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(DROPOUT_SCHEDULE[-1]))
    model.add(layers.Dense(1, activation='sigmoid'))

    # ── Optimizer selection (SGD needs higher LR + momentum to compete) ─────
    if optimizer_name == 'adam':
        opt = keras.optimizers.Adam(learning_rate=BASE_LR)
    elif optimizer_name == 'adamw':
        opt = keras.optimizers.AdamW(learning_rate=BASE_LR, weight_decay=1e-4)
    elif optimizer_name == 'sgd':
        opt = keras.optimizers.SGD(learning_rate=BASE_LR, momentum=0.9, nesterov=True)
    elif optimizer_name == 'rmsprop':
        opt = keras.optimizers.RMSprop(learning_rate=BASE_LR)
    else:
        raise ValueError(f"Unknown optimizer: {optimizer_name}")

    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# ── COSINE DECAY (used for all optimizers, same schedule) ───────────────────
def make_cosine_scheduler(base_lr, total_epochs):
    def cosine_decay(epoch, lr):
        return base_lr * 0.5 * (1 + np.cos(np.pi * epoch / total_epochs))
    return LearningRateScheduler(cosine_decay, verbose=0)

# ── LOOP THROUGH OPTIMIZERS ──────────────────────────────────────────────────
results = {}
histories = {}

for opt_name in OPTIMIZERS_TO_TEST:
    print(f'\n{"="*60}\nTRAINING WITH OPTIMIZER: {opt_name.upper()}\n{"="*60}')

    model = build_model(opt_name, IMG_SIZE)

    callbacks = [
        EarlyStopping(monitor='val_loss', patience=ES_PATIENCE, min_delta=ES_MIN_DELTA,
                      restore_best_weights=True, verbose=0),
        ModelCheckpoint(f'best_model_{opt_name}.h5', monitor='val_accuracy',
                         save_best_only=True, verbose=0),
        make_cosine_scheduler(BASE_LR, EPOCHS),
    ]

    start_time = time.time()
    history = model.fit(
        train_ds_prepped, validation_data=val_ds_prepped,
        epochs=EPOCHS, callbacks=callbacks, verbose=1
    )
    elapsed = time.time() - start_time

    test_loss, test_acc = model.evaluate(val_ds_prepped, verbose=0)
    train_acc_final = history.history['accuracy'][-1]
    val_acc_final = history.history['val_accuracy'][-1]
    gap = train_acc_final - val_acc_final
    epochs_run = len(history.history['loss'])

    results[opt_name] = dict(
        val_acc=test_acc, val_loss=test_loss, train_acc=train_acc_final,
        gap=gap, epochs_run=epochs_run, time_sec=elapsed,
        time_per_epoch=elapsed/epochs_run
    )
    histories[opt_name] = history

    print(f'\n[{opt_name.upper()}] Val Acc: {test_acc:.4f} | Train Acc: {train_acc_final:.4f} | '
          f'Gap: {gap:.4f} | Epochs: {epochs_run} | Time: {elapsed:.1f}s '
          f'({elapsed/epochs_run:.1f}s/epoch)')

# ── FINAL COMPARISON: TRAINING vs VALIDATION EFFICIENCY ──────────────────────
print(f'\n{"="*80}\nFINAL OPTIMIZER COMPARISON — TRAINING & VALIDATION EFFICIENCY\n{"="*80}')
print(f'{"Optimizer":<10}{"TrainAcc":<10}{"ValAcc":<10}{"ValLoss":<10}{"Gap":<8}'
      f'{"Epochs":<8}{"Time(s)":<10}{"s/Epoch":<8}')
for opt_name, r in results.items():
    print(f'{opt_name:<10}{r["train_acc"]:<10.4f}{r["val_acc"]:<10.4f}{r["val_loss"]:<10.4f}'
          f'{r["gap"]:<8.4f}{r["epochs_run"]:<8}{r["time_sec"]:<10.1f}{r["time_per_epoch"]:<8.1f}')

best_acc = max(results, key=lambda k: results[k]['val_acc'])
fastest = min(results, key=lambda k: results[k]['time_per_epoch'])
print(f'\nBest validation accuracy: {best_acc.upper()} ({results[best_acc]["val_acc"]:.4f})')
print(f'Fastest per-epoch training: {fastest.upper()} ({results[fastest]["time_per_epoch"]:.1f}s/epoch)')

# ── COMPARISON PLOTS ──────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

for opt_name, h in histories.items():
    axes[0].plot(h.history['val_accuracy'], label=f'{opt_name} (val={results[opt_name]["val_acc"]:.4f})')
axes[0].set_title('Validation Accuracy by Optimizer')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Val Accuracy')
axes[0].legend(); axes[0].grid(True)

for opt_name, h in histories.items():
    axes[1].plot(h.history['val_loss'], label=opt_name)
axes[1].set_title('Validation Loss by Optimizer')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Val Loss')
axes[1].legend(); axes[1].grid(True)

plt.tight_layout(); plt.show()

# Bar chart: time efficiency vs accuracy tradeoff
fig, ax1 = plt.subplots(figsize=(10, 5))
opt_names_list = list(results.keys())
val_accs = [results[o]['val_acc'] for o in opt_names_list]
times = [results[o]['time_per_epoch'] for o in opt_names_list]

x = np.arange(len(opt_names_list))
ax1.bar(x - 0.2, val_accs, 0.4, label='Val Accuracy', color='steelblue')
ax1.set_ylabel('Validation Accuracy', color='steelblue')
ax1.set_xticks(x); ax1.set_xticklabels([o.upper() for o in opt_names_list])

ax2 = ax1.twinx()
ax2.bar(x + 0.2, times, 0.4, label='Sec/Epoch', color='orange')
ax2.set_ylabel('Seconds per Epoch', color='orange')

plt.title('Accuracy vs Training Speed Tradeoff by Optimizer')
fig.tight_layout(); plt.show()

# ============================================================================
# CATS vs DOGS — CNN HYPERPARAMETER EXPERIMENTS (AUTO LOOP: E → F → G)
# FULLY REPRODUCIBLE VERSION — same results every re-run
# ============================================================================

# ── STEP 0: SET SEEDS BEFORE ANYTHING ELSE IMPORTS TENSORFLOW ─────────────
# This MUST run before `import tensorflow` for full effect (hash seed env var
# only works if set before the process touches any hashing-dependent imports)
import os
SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_DETERMINISTIC_OPS'] = '1'     # forces deterministic GPU kernels
os.environ['TF_CUDNN_DETERMINISTIC'] = '1'   # forces deterministic cuDNN convs

!pip install kagglehub -q

import kagglehub, time
path = kagglehub.dataset_download("haroon669/cats-vs-dogs-dataset-10k-cat-10k-dog-images")
print("Dataset downloaded to:", path)

import random
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, LearningRateScheduler

# ── STEP 1: SEED EVERY RNG SOURCE ──────────────────────────────────────────
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)
tf.keras.utils.set_random_seed(SEED)   # convenience wrapper: sets python/np/tf seeds together

# ── STEP 2: FORCE DETERMINISTIC OPS (TF 2.8+) ──────────────────────────────
# Without this, some GPU ops (e.g. certain conv/pooling backprop kernels) pick
# nondeterministic algorithms for speed, which alone can change results
# epoch-to-epoch even with all seeds fixed. This can slow training slightly.
tf.config.experimental.enable_op_determinism()

print('TF version:', tf.__version__)

IMG_SIZE = 128
BATCH_SIZE = 32
USE_BATCH_NORM = True
USE_AUGMENTATION = True
ES_PATIENCE = 8
ES_MIN_DELTA = 0.001
LR_PATIENCE = 4
LR_FACTOR = 0.5
LR_MIN = 1e-6

CONFIGS = {
    'E': dict(conv_filters=[32,64,128,256], dropout_schedule=[0.2,0.25,0.3,0.3],
              pooling='avg', optimizer='adam', lr=0.001, lr_schedule='cosine',
              dense_units=256, epochs=100),

    'F': dict(conv_filters=[32,64,128,256,512], dropout_schedule=[0.15,0.2,0.25,0.3,0.35],
              pooling='avg', optimizer='adamw', lr=0.001, lr_schedule='plateau',
              dense_units=512, epochs=100),

    'G': dict(conv_filters=[32,64,128,256], dropout_schedule=[0.2,0.25,0.3,0.3],
              pooling='avg', optimizer='adam', lr=0.001, lr_schedule='cosine',
              dense_units=512, epochs=100),
}

# ── DATA (loaded once, reused across all experiments) ──────────────────────
# shuffle uses `seed=SEED` so the train/val split order is identical every run
train_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'train'), seed=SEED, shuffle=True,
    image_size=(IMG_SIZE, IMG_SIZE), batch_size=BATCH_SIZE, label_mode='binary')

val_ds = keras.utils.image_dataset_from_directory(
    os.path.join(path, 'test'), seed=SEED, shuffle=False,
    image_size=(IMG_SIZE, IMG_SIZE), batch_size=BATCH_SIZE, label_mode='binary')

class_names = train_ds.class_names
print('Classes:', class_names)

normalization_layer = layers.Rescaling(1./255)

# ── STEP 3: SEED THE AUGMENTATION LAYERS THEMSELVES ────────────────────────
# RandomFlip/RandomRotation/RandomZoom each draw their own random numbers per
# batch. Without an explicit seed they use a fresh random generator every run
# -> different flips/rotations/zooms -> different final accuracy each time.
data_augmentation = keras.Sequential([
    layers.RandomFlip('horizontal', seed=SEED),
    layers.RandomRotation(0.1, seed=SEED),
    layers.RandomZoom(0.1, seed=SEED),
], name='augmentation')

def prepare(ds, training=False):
    ds = ds.map(lambda x, y: (normalization_layer(x), y))
    if training and USE_AUGMENTATION:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y))
    return ds.prefetch(tf.data.AUTOTUNE)

train_ds_prepped = prepare(train_ds, training=True)
val_ds_prepped = prepare(val_ds, training=False)

# ── MODEL BUILDER ─────────────────────────────────────────────────────────
def build_model(cfg, exp_name, img_size):
    # re-seed right before building each model so weight initialization
    # (Conv2D/Dense kernel_initializer) is identical across re-runs too
    tf.keras.utils.set_random_seed(SEED)

    model = keras.Sequential(name=f'CatsDogs_Exp_{exp_name}')

    for i, (filters, drop) in enumerate(zip(cfg['conv_filters'], cfg['dropout_schedule'])):
        if i == 0:
            model.add(layers.Conv2D(filters, (3,3), activation='relu', padding='same',
                                     input_shape=(img_size, img_size, 3)))
        else:
            model.add(layers.Conv2D(filters, (3,3), activation='relu', padding='same'))
        if USE_BATCH_NORM:
            model.add(layers.BatchNormalization())
        model.add(layers.MaxPooling2D((2,2)))
        model.add(layers.Dropout(drop, seed=SEED))

    if cfg['pooling'] == 'avg':
        model.add(layers.GlobalAveragePooling2D())
    else:
        model.add(layers.GlobalMaxPooling2D())

    model.add(layers.Dense(cfg['dense_units'], activation='relu'))
    if USE_BATCH_NORM:
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(cfg['dropout_schedule'][-1], seed=SEED))
    model.add(layers.Dense(1, activation='sigmoid'))

    if cfg['optimizer'] == 'adam':
        opt = keras.optimizers.Adam(learning_rate=cfg['lr'])
    elif cfg['optimizer'] == 'adamw':
        opt = keras.optimizers.AdamW(learning_rate=cfg['lr'], weight_decay=1e-4)
    elif cfg['optimizer'] == 'sgd':
        opt = keras.optimizers.SGD(learning_rate=cfg['lr'], momentum=0.9, nesterov=True)
    elif cfg['optimizer'] == 'rmsprop':
        opt = keras.optimizers.RMSprop(learning_rate=cfg['lr'])
    else:
        raise ValueError(f"Unknown optimizer: {cfg['optimizer']}")

    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# ── AUTO LOOP THROUGH E, F, G ────────────────────────────────────────────────
results = {}
histories = {}
trained_models = {}

for exp_name, cfg in CONFIGS.items():
    print(f'\n{"="*70}\nTRAINING EXPERIMENT {exp_name}: {cfg}\n{"="*70}')

    model = build_model(cfg, exp_name, IMG_SIZE)
    model.summary()

    callbacks = [
        EarlyStopping(monitor='val_loss', patience=ES_PATIENCE, min_delta=ES_MIN_DELTA,
                      restore_best_weights=True, verbose=1),
        ModelCheckpoint(f'best_model_exp{exp_name}.h5', monitor='val_accuracy',
                         save_best_only=True, verbose=0),
    ]

    if cfg['lr_schedule'] == 'plateau':
        callbacks.append(ReduceLROnPlateau(monitor='val_loss', factor=LR_FACTOR,
                                            patience=LR_PATIENCE, min_lr=LR_MIN, verbose=1))
    elif cfg['lr_schedule'] == 'cosine':
        def cosine_decay(epoch, lr, base_lr=cfg['lr'], total_epochs=cfg['epochs']):
            return base_lr * 0.5 * (1 + np.cos(np.pi * epoch / total_epochs))
        callbacks.append(LearningRateScheduler(cosine_decay, verbose=1))

    start_time = time.time()
    history = model.fit(
        train_ds_prepped, validation_data=val_ds_prepped,
        epochs=cfg['epochs'], callbacks=callbacks, verbose=1
    )
    elapsed = time.time() - start_time
    actual_epochs = len(history.history['loss'])

    print(f'\n[{exp_name}] Training stopped after {actual_epochs} epochs (max was {cfg["epochs"]})')
    print(f'[{exp_name}] Total training time: {elapsed:.1f}s ({elapsed/actual_epochs:.1f}s/epoch)')

    # ── Evaluate ──────────────────────────────────────────────────────────
    test_loss, test_acc = model.evaluate(val_ds_prepped, verbose=0)
    train_acc_final = history.history['accuracy'][-1]
    val_acc_final = history.history['val_accuracy'][-1]
    gap = train_acc_final - val_acc_final

    print(f'[{exp_name}] Validation Accuracy: {test_acc:.4f} | Loss: {test_loss:.4f}')

    # ── Individual plots: accuracy / loss / LR ───────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(18, 4))
    axes[0].plot(history.history['accuracy'], label='Train Acc')
    axes[0].plot(history.history['val_accuracy'], label='Val Acc')
    axes[0].set_title(f'Accuracy (Exp {exp_name})'); axes[0].legend(); axes[0].grid(True)

    axes[1].plot(history.history['loss'], label='Train Loss')
    axes[1].plot(history.history['val_loss'], label='Val Loss')
    axes[1].set_title('Loss'); axes[1].legend(); axes[1].grid(True)

    lr_key = 'lr' if 'lr' in history.history else None
    if lr_key:
        axes[2].plot(history.history[lr_key], color='green', marker='o', markersize=4)
        axes[2].set_title('LR Schedule'); axes[2].set_yscale('log'); axes[2].grid(True)

    plt.suptitle(f'Exp {exp_name}: filters={cfg["conv_filters"]}, opt={cfg["optimizer"]}, '
                 f'pooling={cfg["pooling"]}, dense={cfg["dense_units"]}', fontsize=11)
    plt.tight_layout(); plt.show()

    # ── Overfitting check ─────────────────────────────────────────────────
    print(f'[{exp_name}] Accuracy Gap: {gap:.4f} -- '
          + ('WARNING: possible overfitting' if gap > 0.05
             else 'GOOD generalization' if gap < 0.02 else 'MODERATE gap'))

    # ── Sample predictions ────────────────────────────────────────────────
    images_batch, labels_batch = next(iter(val_ds_prepped))
    predictions = model.predict(images_batch[:25])
    predicted_classes = (predictions > 0.5).astype(int).flatten()
    confidence_scores = np.where(predictions.flatten() > 0.5, predictions.flatten(), 1 - predictions.flatten())
    true_classes = labels_batch.numpy().flatten().astype(int)[:25]

    plt.figure(figsize=(16, 8))
    for i in range(min(25, len(images_batch))):
        plt.subplot(5, 5, i + 1)
        plt.imshow(images_batch[i].numpy())
        correct = predicted_classes[i] == true_classes[i]
        color = 'green' if correct else 'red'
        plt.title(
            f'P:{class_names[predicted_classes[i]]} ({confidence_scores[i]:.0%})\nT:{class_names[true_classes[i]]}',
            color=color, fontsize=8
        )
        plt.axis('off')
    plt.suptitle(f'Experiment {exp_name}: Sample Predictions', fontsize=12)
    plt.tight_layout(); plt.show()

    # ── Store results ─────────────────────────────────────────────────────
    results[exp_name] = dict(
        val_acc=test_acc, val_loss=test_loss, train_acc=train_acc_final,
        gap=gap, epochs_run=actual_epochs, time_sec=elapsed,
        time_per_epoch=elapsed/actual_epochs,
        best_val_acc=max(history.history['val_accuracy'])
    )
    histories[exp_name] = history
    trained_models[exp_name] = model

# ── FINAL COMPARISON TABLE ─────────────────────────────────────────────────
print(f'\n{"="*90}\nFINAL COMPARISON — ALL EXPERIMENTS\n{"="*90}')
print(f'{"Exp":<6}{"TrainAcc":<10}{"ValAcc":<10}{"BestVal":<10}{"ValLoss":<10}'
      f'{"Gap":<8}{"Epochs":<8}{"Time(s)":<10}{"s/Epoch":<8}')
for exp_name, r in results.items():
    print(f'{exp_name:<6}{r["train_acc"]:<10.4f}{r["val_acc"]:<10.4f}{r["best_val_acc"]:<10.4f}'
          f'{r["val_loss"]:<10.4f}{r["gap"]:<8.4f}{r["epochs_run"]:<8}'
          f'{r["time_sec"]:<10.1f}{r["time_per_epoch"]:<8.1f}')

best_exp = max(results, key=lambda k: results[k]['val_acc'])
fastest_exp = min(results, key=lambda k: results[k]['time_per_epoch'])
print(f'\nBest validation accuracy: Experiment {best_exp} ({results[best_exp]["val_acc"]:.4f})')
print(f'Fastest per-epoch training: Experiment {fastest_exp} ({results[fastest_exp]["time_per_epoch"]:.1f}s/epoch)')

# ── COMPARISON PLOTS ─────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

for exp_name, h in histories.items():
    axes[0].plot(h.history['val_accuracy'], label=f'{exp_name} (val={results[exp_name]["val_acc"]:.4f})')
axes[0].set_title('Validation Accuracy — All Experiments')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Val Accuracy')
axes[0].legend(); axes[0].grid(True)

for exp_name, h in histories.items():
    axes[1].plot(h.history['val_loss'], label=exp_name)
axes[1].set_title('Validation Loss — All Experiments')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Val Loss')
axes[1].legend(); axes[1].grid(True)

plt.tight_layout(); plt.show()

# Bar chart: accuracy vs training time tradeoff
fig, ax1 = plt.subplots(figsize=(10, 5))
exp_list = list(results.keys())
val_accs = [results[e]['val_acc'] for e in exp_list]
times = [results[e]['time_per_epoch'] for e in exp_list]

x = np.arange(len(exp_list))
ax1.bar(x - 0.2, val_accs, 0.4, label='Val Accuracy', color='steelblue')
ax1.set_ylabel('Validation Accuracy', color='steelblue')
ax1.set_xticks(x); ax1.set_xticklabels(exp_list)

ax2 = ax1.twinx()
ax2.bar(x + 0.2, times, 0.4, label='Sec/Epoch', color='orange')
ax2.set_ylabel('Seconds per Epoch', color='orange')

plt.title('Accuracy vs Training Speed Tradeoff — All Experiments')
fig.tight_layout(); plt.show()

